### PR TITLE
Publishing to maven central

### PR DESCRIPTION
**Pull request by adrian-kong**
# Description

@swift-nav/devinfra

Releases java with

```
gradle publish
```

requires the account which should be in lastpass as well as a gpg key 

and usage would be:

```
<dependency>
  <groupId>com.swiftnav</groupId>
  <artifactId>sbp</artifactId>
  <version>1.0.0</version>
</dependency>
```

I think it should be searchable at https://search.maven.org/artifact/com.swiftnav/sbp when the site gets indexed

# JIRA Reference

https://swift-nav.atlassian.net/browse/DEVINFRA-294

### CODE REVIEW

**Comment by adrian-kong** [comment]
removed installing gradle from workflow because it was downloading 4.5.1 which didn't support java method for the generator test. not sure if it broke anything

**Review by silverjam — COMMENTED** [review]
A few requests (from our meeting):
- Let's update docs with what's needed to release (what accounts, gpg keys, etc)
- The process for releasing, even if it's partially manual
- Make released version number match the version number in the repository

**Comment by silverjam** [comment]
@adrian-kong let's move the Java publishing instructions to the HOWTO.md in this repo

**Comment by notoriaga** [comment]
@silverjam we are getting errors from apt-get when building the docker image with ubuntu groovy. groovy is end of life, can we just remove it? or should we look into it more

**Comment by silverjam** [comment]
> @silverjam we are getting errors from apt-get when building the docker image with ubuntu groovy. groovy is end of life, can we just remove it? or should we look into it more

Yeah, feel free to remove it, let's add a Jira introduce Jammy (22.04) at some point too.

**Review by silverjam — APPROVED** [review]

**Pull request merged**
