### PR TITLE
hide 'fd is not an integer' error

### PR DESCRIPTION
**Pull request by scottswift**

### CODE REVIEW

**Comment by mookerji** [comment]
@scottswift what's the context of this bugfix?

**Comment by scottswift** [comment]
running serial_link on timon in the capture script leads to many file descriptor errors that don't seem to be fatal. this passes them through as IOErrors, but I didn't diagnose the underlying problem

**Comment by JoshuaGross** [comment]
should we merge this or punt it?

**Comment by mookerji** [comment]
My thought is punt? I want to understand what the actual problem is instead of paper over it?

**Pull request closed without merging**
