### PR TITLE
Update SBP Docs to Include GNSS Signals Table [DEVINFRA-661] (#1124)

### PR DESCRIPTION
**Pull request by isaactorz**
Adds a table to the libsbp pdf that explicitly lists all the GNSS Signals
we support (or intend to support).

The message fields that referenced the old, incomplete table (derived from
a bitfield), have been updated to have a link to the new table.

Cherry-picked from: 7763b73f2aa6891a57dd47656677bb6bfe2668f5 per request from @larrychangSN 

# Description

@swift-nav/devinfra

# API compatibility

Does this change introduce a API compatibility risk?

No this only changes the documentation.

## API compatibility plan

If the above is "Yes", please detail the compatibility (or migration) plan:

# JIRA Reference

No jira ticket.

### CODE REVIEW

**Comment by isaactorz** [comment]
@silverjam Any idea what this build error is ^^ ? `make html-python` ran successfully for me in the build container.

**Comment by silverjam** [comment]
A lot of things are not containerized in GHA, so we occasionally get hit with build breakages from non-backwards compatible tool updates... in this case I think the build error is this:

```
Warning, treated as error:
Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
Creating file ./sbp.rst.
Creating file ./sbp.acquisition.rst.
Creating file ./sbp.bootload.rst.
```

**Comment by silverjam** [comment]
In this branch we use `langauge = None` see:
https://github.com/swift-nav/libsbp/blob/libsbp-v3.4.11-release/python/docs/source/conf.py#L73

In master we use `language = "en"` see:
https://github.com/swift-nav/libsbp/blob/master/python/docs/source/conf.py#L81

**Comment by silverjam** [comment]
just close to close this for now since CI needs some work

**Pull request closed without merging**
