### PR TITLE
C bindings: Allow multiple callbacks for a message.  

### PR DESCRIPTION
**Pull request by gsmcmullin**
And add function to remove a callback.

/cc @jacobmcnamee

### CODE REVIEW

**Comment by JoshuaGross** [comment]
This is great! Test is failing, relevant lines (?):

```
/home/travis/build/swift-nav/libsbp/c/test/check_sbp.c: In function ‘test_sbp_process’:
/home/travis/build/swift-nav/libsbp/c/test/check_sbp.c:157:3: error: implicit declaration of function ‘sbp_find_callback’ [-Werror=implicit-function-declaration]
/home/travis/build/swift-nav/libsbp/c/test/check_sbp.c: In function ‘test_callbacks’:
/home/travis/build/swift-nav/libsbp/c/test/check_sbp.c:382:3: error: comparison between pointer and integer [-Werror]
/home/travis/build/swift-nav/libsbp/c/test/check_sbp.c:385:3: error: invalid type argument of ‘->’ (have ‘int’)
/home/travis/build/swift-nav/libsbp/c/test/check_sbp.c:397:3: error: comparison between pointer and integer [-Werror]
/home/travis/build/swift-nav/libsbp/c/test/check_sbp.c:400:3: error: invalid type argument of ‘->’ (have ‘int’)
/home/travis/build/swift-nav/libsbp/c/test/check_sbp.c:403:3: error: comparison between pointer and integer [-Werror]
/home/travis/build/swift-nav/libsbp/c/test/check_sbp.c:406:3: error: invalid type argument of ‘->’ (have ‘int’)
/home/travis/build/swift-nav/libsbp/c/test/check_sbp.c: At top level:
cc1: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]
cc1: all warnings being treated as errors
```

**Comment by JoshuaGross** [comment]
@mookerji @mfine any opposition to bringing this in? This changes the C API so should we bump this to `1.2.0` or `2.0.0`?

**Comment by mookerji** [comment]
It doesn't changed the messaging wire format, just the internal details of the C library. I think it would actually bump the minor version of the C library, if one exists.

**Comment by JoshuaGross** [comment]
So far we've been keeping all the version numbers in lockstep, which I'd like to continue doing. We can bump the minor version number. So `1.2.0` it is?

**Comment by mfine** [comment]
Works for me.

**Comment by mookerji** [comment]
👍

**Comment by gsmcmullin** [comment]
@JoshuaGross @mfine @mookerji Is it ok for me to merge this, or must the version change be part of this PR?

**Comment by mfine** [comment]
Good to merge - then you can tag master with `1.2.0` after the merge.

**Pull request merged**
