### PR TITLE
rust: update to swiftnav 0.6.1

### PR DESCRIPTION
**Pull request by silverjam**

### CODE REVIEW

**Comment by silverjam** [comment]
@notoriaga let me know if this conflicts with your work and I'll close

**Review by notoriaga — APPROVED** [review]
Nope should be good, thanks!

**Comment by notoriaga** [comment]
I got the same 0.0/-0.0 on my pr, not sure what's up with that. Maybe tests in a binary crate don't use the lock file and something in serde_json changed

**Comment by silverjam** [comment]
> I got the same 0.0/-0.0 on my pr, not sure what's up with that. Maybe tests in a binary crate don't use the lock file and something in serde_json changed

I mentioned the issue here https://github.com/serde-rs/json/pull/801 -- but it looks like this might be "correct" behavior since everything in JSON is a float?

**Comment by silverjam** [comment]
To different solutions:
- https://github.com/swift-nav/libsbp/pull/1073/commits/df0da9a60815583bffd797386854b0e7b9d00a00
- https://github.com/swift-nav/libsbp/pull/1073/commits/d380158b16e18ef2345b09f503b13368f414501c

**Pull request merged**
