### PR TITLE
added channel ID tag to spectrum analyzer

### PR DESCRIPTION
**Pull request by mbavaro**
FW has never produced this message, and before it does it might be beneficial to have total overlap with the message defined here https://paper.dropbox.com/doc/Spectrum-Analyzer-Project-OhZuyQq5UvBsZOsw2Osx5 to ease integration in console

### CODE REVIEW

**Comment by mbavaro** [comment]
oh, and it's apparently lifted some other uncommitted changes on Glonass...

**Comment by mfine** [comment]
As long as this has never been emitted yet, should be fine to modify in place. Otherwise, would need to create a new message type, otherwise parsers break.

**Comment by mbavaro** [comment]
I can confirm this has never been produced (in fact I am putting a PR up now in PFWP)....

**Comment by mfine** [comment]
Sounds good.

**Comment by mbavaro** [comment]
thanks Mark, PFWP PR up now... 
https://github.com/swift-nav/piksi_firmware_private/pull/859

**Pull request merged**
