### PR TITLE
Front end gain message

### PR DESCRIPTION
**Pull request by denniszollo**
This PR adds a new SBP message to provide the gain values in RF frontends from Swift Receivers.  Its goal is to provide human friendly messages that can be used to assess receiver health and purposely divorces itself from hardware implementation.  If a future frontend doesn't have an AGC for one of the stages, we have a way to encode it as invalid or missing.

image
@ericsenant @mbavaro @nsirola @fnoble

### CODE REVIEW

**Comment by denniszollo** [comment]
I think I didn't generate all languages after updating description.  I will fix.

**Comment by switanis** [comment]
Max can be 255 not 256 I think.
The usable (valid) range will be 0 to 100. I mean no any scaling. Please confirm.
Otherwise good. I like it.

**Comment by denniszollo** [comment]
@sfefan. I used a signed 8 bit integer and noted that the max value of 127 would mean channel is missing and a negative value would mean some kind of error.  valid range is 0 to 100.

**Comment by switanis** [comment]
Sounds good. Thx.

**Pull request merged**
