### PR TITLE
File playback driver

### PR DESCRIPTION
**Pull request by pmiettinen**
## Motivation
Dennis' comment here https://github.com/swift-nav/piksi_tools/pull/1137#pullrequestreview-361312591

## Related
https://github.com/swift-nav/piksi_tools/pull/1138

## In practice
Playing back from SBP JSON log:
image

### CODE REVIEW

**Comment by pmiettinen** [comment]
Not production worthy yet but good for initial comments if it makes any sense.

**Comment by pmiettinen** [comment]
At least the console/serial_link needs some rearranging to enable the different combinations of the options.

**Comment by pmiettinen** [comment]
If the timestamp metadata is not present, maybe TOW could be utilized instead. Would need to account for rollovers though.

**Comment by silverjam** [comment]
@pmiettinen I believe we're fine to merge this

**Pull request merged**
