### PR TITLE
fix new rust lints

### PR DESCRIPTION
**Pull request by pcrumley**
# Description

@swift-nav/algint-team -- maybe fixes new rust lints

# API compatibility

Does this change introduce a API compatibility risk?

## API compatibility plan

If the above is "Yes", please detail the compatibility (or migration) plan:

# JIRA Reference

https://swift-nav.atlassian.net/browse/BOARD-XXXX

### CODE REVIEW

**Review by sokhealy — APPROVED** [review]
looks good, thanks for fixing the linting issue!

**Comment by pcrumley** [comment]
@sokhealy can you approve it?

**Comment by sokhealy** [comment]
> @sokhealy can you approve it?

I already did,

**Review by sokhealy — APPROVED** [review]
second approval?

**Comment by sokhealy** [comment]
I can approve as part of @swift-nav/algint-team , but it looks like it's also waiting for @notoriaga's approval?

**Comment by pcrumley** [comment]
@sokhealy this is silly. I'm just going to bypass branch protections because the change is trivial, and it is failing the macos stage anyway

**Pull request merged**
