### PR TITLE
Put memory packing outside the COMMON_INT_TYPES macro

### PR DESCRIPTION
**Pull request by mbavaro**
When combined with LSN/common.h the current arrangement causes quite a bit of problems..

### CODE REVIEW

**Comment by mfine** [comment]
Man, I'm not good with this stuff - I think @denniszollo had something around this https://github.com/swift-nav/libsbp/pull/479 back in the day.

**Comment by mbavaro** [comment]
When compiling code that has dependencies with both `libswiftnav` and `libsbp`, one bumps on this 

https://github.com/swift-nav/libswiftnav/blob/master/include/libswiftnav/common.h#L30

which defines our int types (`s8`, `u16`, ...) and just those. 
However, the `#ifdef` in libsbp holds these packing pragmas too..

https://github.com/swift-nav/libsbp/blob/master/c/include/libsbp/common.h#L27-L48

So depending on the include order (if the LSN `common.h` is included first) those aren't seen by the pre-compiler and so a bunch of declarations like 
https://github.com/swift-nav/libsbp/blob/master/c/include/libsbp/gnss.h#L28
and 
https://github.com/swift-nav/libsbp/blob/master/c/include/libsbp/gnss.h#L48
throw errors...
I don't see why those pre-processor macros should go inside `COMMON_INT_TYPES`.. I must be missing something?

**Comment by silverjam** [comment]
@mbavaro I wanted to double check the actual error, but given that, this change looks correct, it definitely makes sense that it shouldn't be inside the `COMMON_INT_TYPES` guard.

**Comment by denniszollo** [comment]
Don't we need another preprocessor guard so these macros aren't redefined each time the file is included then ?

**Comment by denniszollo** [comment]
My bad team.  Glad you sorted it out.

**Pull request merged**
