### PR TITLE
Updating libraries and license to 2022

### PR DESCRIPTION
**Pull request by adrian-kong**
# Description

@swift-nav/devinfra

Small update to the libraries and the license header to 2022

# API compatibility

It should still be compatible, no changes in API.

### CODE REVIEW

**Review by joelynch — COMMENTED** [review]
Looks good to me.  Is there a JIRA task for this one?

**Comment by adrian-kong** [comment]
> Looks good to me. Is there a JIRA task for this one?

nope just a quick and tiny update

**Review by joelynch — APPROVED** [review]
Looks good to me

**Review by samvrlewis — APPROVED** [review]

**Review by silverjam — CHANGES_REQUESTED** [review]
Since most files in this repository are generated you'll need to update the template file that generates everything in order for this change to persist please see here for the correct location to update the generated files:

https://github.com/swift-nav/libsbp/blob/master/generator/sbpg/targets/resources/sbp_java.java.j2#L2

After updating the template you can run the generator in order to check that it generates the correct output, in your checkout of the libsbp repo, run the following:

```
docker run  -v $PWD:/mnt/workspace -i -t swiftnav/libsbp-build:2021-10-13 /bin/bash -c "make java"
```

**Comment by adrian-kong** [comment]
oops i think i broke the branch

**Pull request closed without merging**
