### PR TITLE
Unit documentation improvements [DEVINFRA-833]

### PR DESCRIPTION
**Pull request by richarddeurloo**

### CODE REVIEW

**Comment by silverjam** [comment]
@richarddeurloo Do we still need this?

**Comment by richarddeurloo** [comment]
@silverjam As a whole we don't need it anymore. But I'm wondering if part of the commits (at least a1a63a7) should be merged into master. If you don't mind, I'd like to keep it open for the moment. I'll check if part of it can be merged into master.

**Comment by silverjam** [comment]
@richarddeurloo can we close this or move it into a Jira ticket?

**Comment by silverjam** [comment]
@adrian-kong for next sprint, let's just undo the changes to the `public` field and the `gnss` module, I think we can port everything else over to current master

**Comment by adrian-kong** [comment]
> @adrian-kong for next sprint, let's just undo the changes to the `public` field and the `gnss` module, I think we can port everything else over to current master

It looks like most of the things on master / conflicts already applies changes, don't think we need this unless we just want the desc to be bracketed or something

**Pull request closed without merging**
