### PR TITLE
[STEP-217] Add timestamped versions of resource usage messages

### PR DESCRIPTION
**Pull request by IsakTjernberg**
### Background
New versions of the Linux resource usage messages, with the addition of timestamps.
See section in [design doc](https://swift-nav.atlassian.net/wiki/spaces/~908386495/pages/1416070105/STEP+usability+-+resource+usage+output+design+doc#New-SBP-messages).
Also fixes a typo in a previously existing message.

The changes are split into two commits for easier review, the first one is for updating the YAML spec and the second commit holds all the changes as automatically generated by the `make` step. Will squash them on merge.

### CODE REVIEW

**Review by dgburr — APPROVED** [review]
Should the old (non-timestamped) messages be marked as deprecated?

**Comment by silverjam** [comment]
> 
> 
> Should the old (non-timestamped) messages be marked as deprecated?

Changes look good, and yes, we should follow the existing convention of renaming the old messages to `_DEP_A` and have the new messages take the name of the old messages.

FYI, if the Rust build fails, the workaround is to clear the caches on Travis.  Hopefully this issue will be gone once we merge #905 (cc @notoriaga).

**Comment by IsakTjernberg** [comment]
Alright, I made the old ids deprecated and re-used their names for the new messages.
@silverjam How do I clear the cache on Travis? Do I need to be signed in there to see that option somewhere? I haven't authorized Travis with my Github account and don't know if I should.

**Comment by silverjam** [comment]
> 
> 
> Alright, I made the old ids deprecated and re-used their names for the new messages.
> @silverjam How do I clear the cache on Travis? Do I need to be signed in there to see that option somewhere? I haven't authorized Travis with my Github account and don't know if I should.

It's fine to authorize your account with Travis, it's still used for quite a few things (even though we're trying to phase it out).  Once you log in the cache control is pretty easy to find:



Then:

Screenshot 2021-02-26 163702

**Review by silverjam — APPROVED** [review]

**Pull request merged**
