### PR TITLE
Implement HasTime for Frames [DEVINFRA-516]

### PR DESCRIPTION
**Pull request by adrian-kong**
Intended for `with_rover_time`, important to not do redundant `to_sbp` calls after, so this just assumes that we want

`(Frame,  Time)`
since we cant easily convert from sbp -> frame,

or maybe alternatively we can retain frame and sbp.

This is so that we can do 
`Framer::new(...).with_rover_time()` for `(Frame, Time)` tuple
instead of only 
`sbp::iter_messages(...).with_rover_time()` for `(Sbp, Time)` tuple

### CODE REVIEW

**Review by joelynch — APPROVED** [review]
Seems good

**Comment by notoriaga** [comment]
One thing that bothers me a bit about this is that if you have 

```rust
for (frame, time) in Framer::new(...).with_rover_time() {
    ....
    let msg = frame.to_sbp();
    ...
}
```

you end up converting the frame twice.

> or maybe alternatively we can retain frame and sbp.

would avoid that, but not sure what a clean way to do that is. maybe we could add a method to `Framer` that returns both

```rust
impl Framer {
    pub fn with_messages(self) -> impl Iterator<Item=(Frame, Result<Sbp>)> {
        self.map(|f| (f, f.to_sbp()))
    }
}
```

and then you can impl `HasTime` for `(Frame, Result<Sbp>)` as well. Either way I think it's fine as is

**Review by notoriaga — APPROVED** [review]

**Comment by silverjam** [comment]
> 



> One thing that bothers me a bit about this is that if you have
> 
> ```rust
> for (frame, time) in Framer::new(...).with_rover_time() {
>     ....
>     let msg = frame.to_sbp();
>     ...
> }
> ```
> 
> you end up converting the frame twice.
> 
> > or maybe alternatively we can retain frame and sbp.
> 
> would avoid that, but not sure what a clean way to do that is. maybe we could add a method to `Framer` that returns both
> 
> ```rust
> impl Framer {
>     pub fn with_messages(self) -> impl Iterator<Item=(Frame, Result<Sbp>)> {
>         self.map(|f| (f, f.to_sbp()))
>     }
> }
> ```
> 
> and then you can impl `HasTime` for `(Frame, Result<Sbp>)` as well. Either way I think it's fine as is

Let's track with an issue and revisit @adrian-kong

**Review by silverjam — APPROVED** [review]

**Comment by adrian-kong** [comment]
created https://swift-nav.atlassian.net/browse/DEVINFRA-1028

**Pull request merged**
