### PR TITLE
Move off GnssSignal

### PR DESCRIPTION
**Pull request by mfine**
GnssSignal is a PRN-1 value - GnssSignal16 is not. Remove the existing GnssSignal messages.

/cc @denniszollo @anth-cole

### CODE REVIEW

**Comment by mfine** [comment]
Note - as this goes ins, I think we should move GnssSignal to GnssSignalDep and GnssSignal16 to GnssSignal.

**Comment by mfine** [comment]
Here's moving from GnssSignal16 to GnssSignal: https://github.com/swift-nav/libsbp/pull/523

**Comment by mfine** [comment]
Impacted messages:

```
New Messages                           >  Deprecated Messages
=====================================  >  ========================================
MSG_ACQ_RESULT               0x2F  47  >  MSG_ACQ_RESULT_DEP_C             0x1F  31
MSG_ACQ_SV_PROFILE           0x2E  46  >  MSG_ACQ_SV_PROFILE_DEP           0x1E  30
MSG_GROUP_DELAY              0x94 148  >  MSG_GROUP_DELAY_DEP_B            0x93 147
MSG_ALMANAC_GPS              0x72 114  >  MSG_ALMANAC_GPS_DEP              0x70 112
MSG_ALMANAC_GLO              0x73 115  >  MSG_ALMANAC_GLO_DEP              0x71 113
MSG_MASK_SATELLITE           0x2B  43  >  MSG_MASK_SATELLITE_DEP           0x1B  27
MSG_TRACKING_STATE_DETAILED  0x21  33  >  MSG_TRACKING_STATE_DETAILED_DEP  0x11  17
MSG_TRACKING_IQ              0x2C  44  >  MSG_TRACKING_IQ_DEP              0x1C  28
```

**Comment by mfine** [comment]
All 3 PRs are passing currently:

https://github.com/swift-nav/libsbp/pull/522
https://github.com/swift-nav/libswiftnav-private/pull/1047
https://github.com/swift-nav/piksi_firmware_private/pull/1355

HITL results:

https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-1543-mission&build_type=pr&firmware_versions=v1.2.0-develop-2017110323-9-g0783328f
https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-1543-mission&build_type=pr&firmware_versions=v1.2.0-develop-2017110323-9-g0783328f

**Comment by mfine** [comment]
Fixes https://github.com/swift-nav/piksi_v3_bug_tracking/issues/826.

I've added the removal of standardization of GPSTime to GPSTimeNano as well.

**Comment by ljbade** [comment]
Sweet! We had hoped to make a clean break with Piksi Multi 1.0 but it didn't quite happen

**Pull request merged**
