### PR TITLE
[SSR-225] Add Satellite APC message

### PR DESCRIPTION
**Pull request by jbangelo**
This adds a message definition for satellite antenna phase center corrections. The message contains the mean phase center offset and elevation dependent variations for a particular satellite signal. The correction data is based on the IGS ANTEX files, and the field definition references the file format where relevant. Due to the small size of the corrections for a single signal multiple corrections can optionally packed into a single SBP frame.

PDF documentation for the new message: 
image

### CODE REVIEW

**Comment by jbangelo** [comment]
As usual I split out the auto-genned files into a separate commit to make reviewing easier.

**Review by silverjam — APPROVED** [review]

**Comment by ljbade** [comment]
I thought you mentioned that different constellations had a different number of PCV values?

**Comment by jbangelo** [comment]
@ljbade The design doc has been updated to address that concern.

**Review by ljbade — APPROVED** [review]

**Comment by silverjam** [comment]
@jbangelo merged?

**Pull request merged**
