### PR TITLE
rust: support encoding borrowed messages 

### PR DESCRIPTION
**Pull request by notoriaga**
needs https://github.com/swift-nav/dencode/pull/2

Makes it so the encoders work with borrowed messages. Adds convenience functions to get a framed writer. Should we reexport dencode so people don't have to bring it in?

### CODE REVIEW

**Comment by notoriaga** [comment]
@john-michaelburke with these changes you can do something like 

```rust
fn test() {
    use dencode::IterSinkExt;

    let input_file = std::fs::File::open("messages").unwrap();
    let log_file = std::fs::File::create("log").unwrap();
    let json_log_file = std::fs::File::create("json_logs").unwrap();

    let mut bin_encoder = SbpEncoder::framed(log_file);
    let mut json_encoder = JsonEncoder::framed(json_log_file, serde_json::ser::CompactFormatter);

    for msg in iter_messages(input_file) {
        let msg = msg.unwrap();

        bin_encoder.send(&msg).unwrap();
        json_encoder.send(&msg).unwrap();
    }
}
```

**Comment by silverjam** [comment]
> ... Should we reexport dencode so people don't have to bring it in?

👍

**Review by silverjam — APPROVED** [review]
contingent on re-exporting dencode

**Review by john-michaelburke — APPROVED** [review]
Thank you for this!!

**Pull request merged**
