### PR TITLE
Specify that 0xFFFF is used to indicate invalid PDOP/HDOP/VDOP

### PR DESCRIPTION
**Pull request by dgburr**

### CODE REVIEW

**Review by reimerix — COMMENTED** [review]
Changes LGTM. Do you need a hand with updating the generated files?

**Comment by dgburr** [comment]
> Changes LGTM. Do you need a hand with updating the generated files?

Yes, it would be great if you could help out (I thought it would be some automatically by Jenkins).

**Comment by reimerix** [comment]
@dgburr I've added the generated files to this PR. You can build them by:
` docker pull swiftnav/libsbp-build:latest-master`
`docker run  -v $(pwd):/mnt/workspace -i -t swiftnav/libsbp-build:latest-master`
and then, in the container:
`make -j16 all`

**Comment by GuillaumeDec** [comment]
> @dgburr I've added the generated files to this PR. You can build them by:
> ` docker pull swiftnav/libsbp-build:latest-master`
> `docker run -v $(pwd):/mnt/workspace -i -t swiftnav/libsbp-build:latest-master`
> and then, in the container:
> `make -j16 all`

`-j16` 🤣 🇩🇪 💣 😂 🥇 !! 
Note: I like to add `--rm` to the `docker run` command to avoid having tens of inactive containers sitting around, unless you wanna keep the container state for some later time of course. But those who can afford `-j16` can afford TB of disk space.... 🤣 🤣

**Review by GuillaumeDec — APPROVED** [review]
LGTM! 🙏

**Pull request merged**
