### PR TITLE
raise StopIteration in receive if the _broken flag is set.

### LINKED ISSUE #325: When using only callbacks, "error: unpack requires a string argument of length 5"
The following code snippet crashes:

```
      with PySerialDriver(self.sbp_port, baud=self.sbp_baud) as driver:
        with Handler(Framer(driver.read, None, verbose=True)) as source:
          source.add_callback(self.handle_incoming)
          while True:
            time.sleep(1.0)
```

It crashes with the following error:

```
Exception in thread Handler:
Traceback (most recent call last):
  File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/njoubert/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sbp-0.52.1-py2.7.egg/sbp/client/handler.py", line 46, in _recv_thread
    for msg, metadata in self._source:
  File "/Users/njoubert/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sbp-0.52.1-py2.7.egg/sbp/client/framer.py", line 67, in next
    msg = self._receive()
  File "/Users/njoubert/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sbp-0.52.1-py2.7.egg/sbp/client/framer.py", line 113, in _receive
    msg_type, sender, msg_len = struct.unpack("<HHB", hdr)
error: unpack requires a string argument of length 5
```

### PR DESCRIPTION
**Pull request by denniszollo**
This should fix #325 
/cc @njoubert @mfine @JoshuaGross

### CODE REVIEW

**Comment by mfine** [comment]
cc @gsmcmullin

**Comment by mookerji** [comment]
@denniszollo man, you're on a roll this week.

**Comment by JoshuaGross** [comment]
Can we merge this?

**Comment by gsmcmullin** [comment]
lgtm

**Pull request merged**
