### PR TITLE
Fixes for Java implementation

### PR DESCRIPTION
**Pull request by gsmcmullin**
- Minor fixes to clear build errors
- Add missing types for S8, S16 and U64
- Remove dead generated classes breaking the build

/cc @zakaswift

### CODE REVIEW

**Comment by zakaswift** [comment]
Thanks Gareth.  Does the Travis build "build" and then "test" the generated classes?

**Comment by JoshuaGross** [comment]
should fix up the travis tests/compilation before merging:

```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/default-java
```

**Comment by owend** [comment]
What's the status of this PR?  The java build in master is broken at the moment.

**Comment by mfine** [comment]
@owend sorry for the delay - library should be building on master now!

**Pull request closed without merging**
