### PR TITLE
Change description for msg_tracking_state_detailed_t.lock

### PR DESCRIPTION
**Pull request by dt-exafore**
Based on https://github.com/swift-nav/exafore_planning/issues/497

### CODE REVIEW

**Comment by dt-exafore** [comment]
@adel-mamin Please, review.

**Comment by ljbade** [comment]
lgtm, but it seems the pdf did not get updated? Can you update the pdf before merge?

**Comment by mfine** [comment]
@ljbade this is not a public message and shouldn't be showing up in the pdf:

https://github.com/swift-nav/libsbp/blob/master/spec/yaml/swiftnav/sbp/tracking.yaml#L24

**Comment by ljbade** [comment]
@mfine oh of course, duh! sorry @adel-mamin this is fine to merge

**Pull request merged**
