### PR TITLE
Deprecate SSR gridded correction message

### PR DESCRIPTION
**Pull request by mfine**
# Description

Add a deprecated SSR gridded correction message so that there are not deprecated and non-deprecated SSR messages composing the SSR atmospheric message.

@swift-nav/devinfra

# API compatibility

Does this change introduce a API compatibility risk?

This removes a API compatibility risk with using a non-deprecated message amongst deprecated messages.

## API compatibility plan

If the above is "Yes", please detail the compatibility (or migration) plan:

# JIRA Reference

https://swift-nav.atlassian.net/browse/BOARD-XXXX

### CODE REVIEW

**Comment by mfine** [comment]
Not all language files have been generated yet.

**Comment by joelynch** [comment]
Hey Mark I was chatting to @theureau recently and discovered that I had misinterpreted the messages intended to be produced from the SsrAtmo message in the integrity project.

Apparently we need to be emitting
- `msg_ssr_gridded_correction_bounds_t`
or
- `msg_ssr_gridded_correction_t`

rather than what I had assumed as

- `msg_ssr_gridded_correction_bounds_t`
- `msg_ssr_gridded_correction_t`
or
- `msg_ssr_gridded_correction_t`

So I think we should deprecate `msg_ssr_gridded_correction_t` but not introduce a new message as it is being replaced by `msg_ssr_gridded_correction_bounds_t`.

Can you confirm this is the case @fpezzinosn and @lkloh ?

I should have a PR up soon that will make some modifications to the SbpDecoder to support this.

**Comment by mfine** [comment]
@joelynch if `msg_ssr_gridded_correction_t` won't be used in the new message path, then you wouldn't need to deprecate it - you'll be able to tell whether you're using deprecated or non-deprecated messages without a "dummy" deprecated message. (even if messages are no longer used, they don't get deprecated - only when there's another message replacing it).

**Comment by fpezzinosn** [comment]
> Apparently we need to be emitting
> 
> * `msg_ssr_gridded_correction_bounds_t`
>   or
> * `msg_ssr_gridded_correction_t`

This is correct. MSG_SSR_GRIDDED_CORRECTION_BOUNDS (1534) is an extension of MSG_SSR_GRIDDED_CORRECTION (1532). So that one message contains the corrections + bounds, instead of only bounds (like the other integrity messages).

**Comment by mfine** [comment]
> This is correct. MSG_SSR_GRIDDED_CORRECTION_BOUNDS (1534) is an extension of MSG_SSR_GRIDDED_CORRECTION (1532). So that one message contains the corrections + bounds, instead of only bounds (like the other integrity messages).

Nice. Then disregard this PR.

**Pull request closed without merging**
