### PR TITLE
Get rid of separate target for static library and stop fiddling BUILD…

### PR DESCRIPTION
**Pull request by martin-swift**
…_SHARED_LIBS flag.

### CODE REVIEW

**Comment by benjaminaltieri** [comment]
Trying understand if this would be breaking any downstream projects, a quick [github search](https://github.com/swift-nav/libsbp/search?q=BUILD_SHARED_LIBS&unscoped_q=BUILD_SHARED_LIBS) definitely shows that if nothing else we should document this change in behavior.

**Comment by nsirola** [comment]
At least firmware builds with minimal changes: https://github.com/swift-nav/piksi_firmware_private/pull/2350

**Comment by martin-swift** [comment]
I want to merge this; @mbavaro has given his approval - last call for objections!

**Comment by benjaminaltieri** [comment]
go for it!

**Pull request merged**
