### PR TITLE
doc revisions

### PR DESCRIPTION
**Pull request by mfine**
Little tweaks to make the doc work. Find the generated doc here:

https://github.com/mfine/libsbp/blob/mfine-doc-tweaks/docs/sbp.pdf

/cc @cbeighley @denniszollo @mookerji

### CODE REVIEW

**Comment by mookerji** [comment]
Man, I could swear we did something to break up that message ID table across two pages.

**Comment by mfine** [comment]
yeah, looks like we've got too many messages now

**Comment by mookerji** [comment]
We should limit our message table to only those that can fit on a single A4 sheet of paper.

**Comment by mookerji** [comment]
Single page is fine, we can fuck with it later.

**Comment by mookerji** [comment]
Add the semantic versioning policy as well? 
https://github.com/mfine/libsbp/blob/mfine-versioning/VERSIONING.md

**Comment by mfine** [comment]
Doc driven development

**Comment by mfine** [comment]
Yeah, we'll add the versioning policy in when its ready - we're just at point release here.

**Comment by mookerji** [comment]
:+1: merge at will.

**Comment by mfine** [comment]
Also, that `cut` line I put in there is super non-portable.. I tried sed, but it puked - will need to revisit.

**Pull request merged**
