### PR TITLE
Clean up the documentation for the new messages [OTA-150]

### PR DESCRIPTION
**Pull request by fpezzinosn**
# Description

@swift-nav/devinfra

Cleaned up the documentation for the new staged messages.

# API compatibility

Does this change introduce a API compatibility risk?

No, just docstrings updates

## API compatibility plan

If the above is "Yes", please detail the compatibility (or migration) plan:

# JIRA Reference

https://swift-nav.atlassian.net/browse/OTA-150

### CODE REVIEW

**Review by fpezzinosn — COMMENTED** [review]
@silverjam After fixing the overflow in the units columns, the message structure table for `MSG SSR GRIDDED CORRECTION BOUNDS`, `MSG SSR ORBIT CLOCK BOUNDS` and `MSG SSR ORBIT CLOCK BOUNDS DEGRADATION` still clips the page. I guess a solution could be to write shorter descriptions, but then I'm afraid some information will be missing from the document.

**Comment by silverjam** [comment]
> @silverjam After fixing the overflow in the units columns, the message structure table for `MSG SSR GRIDDED CORRECTION BOUNDS`, `MSG SSR ORBIT CLOCK BOUNDS` and `MSG SSR ORBIT CLOCK BOUNDS DEGRADATION` still clips the page. I guess a solution could be to write shorter descriptions, but then I'm afraid some information will be missing from the document.

We will need to customize rendering for these messages or move the information elsewhere.  Would it make sense to create a dedicated page/table that explains things in more detail or do we need to leave everything in this table?

**Comment by fpezzinosn** [comment]
> > @silverjam After fixing the overflow in the units columns, the message structure table for `MSG SSR GRIDDED CORRECTION BOUNDS`, `MSG SSR ORBIT CLOCK BOUNDS` and `MSG SSR ORBIT CLOCK BOUNDS DEGRADATION` still clips the page. I guess a solution could be to write shorter descriptions, but then I'm afraid some information will be missing from the document.
> 
> We will need to customize rendering for these messages or move the information elsewhere. Would it make sense to create a dedicated page/table that explains things in more detail or do we need to leave everything in this table?

I've moved the repeated explanations to notes in the description and then added a See Note 1 for those. I also abbreviated some common terms. Now all the tables fit.

**Comment by silverjam** [comment]
Or... maybe need to add a special case for stubbed messages to the validator.

**Pull request merged**
