### PR TITLE
Fixing unconsumed 4096 error sbp2json

### PR DESCRIPTION
**Pull request by adrian-kong**
# Description

Unconsumed 4096 error on sbp2json

# JIRA Reference

https://swift-nav.atlassian.net/browse/DEVINFRA-510

### CODE REVIEW

**Comment by adrian-kong** [comment]
the suggested changes stops the unconsumed 4096 but runs for a long time, not sure how large the file is supposed to be generated but testing this change creates a 1gb json file for a 0.5gb sbp - runs for a long time (was interrupted)

**Comment by notoriaga** [comment]
at some point we removed the JIT support for python and the bindings got _really_ slow, so it might actually be working

**Comment by silverjam** [comment]
What is the behavior of the tool now?

**Comment by adrian-kong** [comment]
we were playing around with handler instead but that generated more messages than the rust version which was odd but the tool is fixed i think, it worked fine with the 10mb file without unconsumed 4096

**Comment by adrian-kong** [comment]
i also made another pull request #1140 which takes out all the manual reading and also fixes the unconsumed 4096

**Review by silverjam — APPROVED** [review]

**Pull request merged**
