### PR TITLE
Add support for murata scha634 to imu aux message

### PR DESCRIPTION
**Pull request by antrikshsrivastava**
# Description

@swift-nav/devinfra

# API compatibility

Does this change introduce a API compatibility risk?

## API compatibility plan

If the above is "Yes", please detail the compatibility (or migration) plan:

# JIRA Reference

https://swift-nav.atlassian.net/browse/BOARD-XXXX

### CODE REVIEW

**Comment by silverjam** [comment]
@antrikshsrivastava Is this ready for review?

**Comment by antrikshsrivastava** [comment]
> @antrikshsrivastava Is this ready for review?

Not yet, it's not all working together yet, although this PR is unlikely to change much

**Comment by silverjam** [comment]
Converted to draft so I'm not notified that this is pending review, please click "Ready for review" once this is finalized

**Review by silverjam — COMMENTED** [review]
lgtm, please re-request review when this is ready for merge

**Review by jithk — APPROVED** [review]
LGTM. Just curious - what caused the change in IMU_TYPE value from `2` to `4`?

**Comment by antrikshsrivastava** [comment]
> LGTM. Just curious - what caused the change in IMU_TYPE value from `2` to `4`?

Because some of the other numbers are taken up by the Android and ICM42670 here: https://github.com/swift-nav/starling/blob/master/starling_util/src/sbp/unpackers.cc#L22

**Comment by antrikshsrivastava** [comment]
@silverjam how do we deal with the conflicts in this repo, I would think the PDF would just get overwritten? What about the RELEASE-VERSION change?

**Comment by silverjam** [comment]
> @silverjam how do we deal with the conflicts in this repo, I would think the PDF would just get overwritten? What about the RELEASE-VERSION change?

Merge in master and resolve all conflicts with "theirs" then regenerate everything.

**Comment by antrikshsrivastava** [comment]
@silverjam this is ready to merge in whenever, I can't merge it even though I have 1 approval

**Review by adrian-kong — APPROVED** [review]
voilà 

EDIT nvm thought u need review from devinfra will need steve or jason

**Comment by antrikshsrivastava** [comment]
Thanks @adrian-kong .. hmm it still says blocked for me:
Merging is blocked
Merging can be performed automatically with 1 approving review.

**Review by silverjam — APPROVED** [review]
Lgtm

**Pull request merged**
