### PR TITLE
Sort JSON by keys [ESD-1169]

### PR DESCRIPTION
**Pull request by pmiettinen**
Sorting is not done by default to avoid decrease in efficiency.

### CODE REVIEW

**Comment by pmiettinen** [comment]
@mfine How big task would it be to add similar option to haskell `sbp2json`? I tried to figure out myself but there's just too much cryptic stuff for a person with near 0 haskell experience.

**Comment by mfine** [comment]
@pmiettinen there's a module [aeson-pretty](http://hackage.haskell.org/package/aeson-pretty-0.8.7/docs/Data-Aeson-Encode-Pretty.html) that can sort the JSON keys on encoding.

But do you need to build it into the utilities? `jq` will do this for you with `-S`:

```sh
➜  c/tests/data git:(bf2cf4b) cat nmea.sbp | sbp2json  | head -2
{"length":24,"status":0,"preamble":85,"sender":48492,"msg_type":175,"setting":"udp_server1\u0000port\u000055558\u0000","payload":"AHVkcF9zZXJ2ZXIxAHBvcnQANTU1NTgA","crc":29999}
{"length":64,"status":0,"preamble":85,"sender":48492,"msg_type":175,"setting":"udp_client0\u0000mode\u0000Disabled\u0000enum:Disabled,RTCMv3 IN,NMEA OUT,SBP\u0000","payload":"AHVkcF9jbGllbnQwAG1vZGUARGlzYWJsZWQAZW51bTpEaXNhYmxlZCxSVENNdjMgSU4sTk1FQSBPVVQsU0JQAA==","crc":58399}
➜  c/tests/data git:(bf2cf4b) cat nmea.sbp | sbp2json  | head -2 | jq -rcS 
{"crc":29999,"length":24,"msg_type":175,"payload":"AHVkcF9zZXJ2ZXIxAHBvcnQANTU1NTgA","preamble":85,"sender":48492,"setting":"udp_server1\u0000port\u000055558\u0000","status":0}
{"crc":58399,"length":64,"msg_type":175,"payload":"AHVkcF9jbGllbnQwAG1vZGUARGlzYWJsZWQAZW51bTpEaXNhYmxlZCxSVENNdjMgSU4sTk1FQSBPVVQsU0JQAA==","preamble":85,"sender":48492,"setting":"udp_client0\u0000mode\u0000Disabled\u0000enum:Disabled,RTCMv3 IN,NMEA OUT,SBP\u0000","status":0}
➜  c/tests/data git:(bf2cf4b) 
```

**Comment by pmiettinen** [comment]
@mfine I think `jq` is enough for my purposes for now. Thanks.

I found the `aeson-pretty` module also myself but I have too many holes in my understanding of the Haskell syntax (among other things) that I didn't figure out how to use it.

**Comment by mfine** [comment]
@pmiettinen the SBP2JSON doesn't take options presently (at the time, that was the idea to keep it simple and based on stdin stdout - probably should have added options support). To keep things as they are, you could do a SBP2PRETTYJSON or something, similar to SBP2JSON, but change the encoding to use aseon-pretty:

https://github.com/swift-nav/libsbp/blob/master/haskell/main/SBP2JSON.hs#L28

**Comment by pmiettinen** [comment]
@mfine `SBP2PRETTYJSON.hs` is now added. Please check what you think. I am still thinking of adding the pretty print config as an optional command line argument.

**Comment by silverjam** [comment]
Would prefer if we can make this a CLI switch for Haskell somehow and expose the Python option through a switch to (I guess) `serial_link`.

**Comment by mfine** [comment]
I'm good with the separate binary for Haskell.

**Comment by silverjam** [comment]
ok, we'll go with your preference @mfine

**Pull request merged**
