### PR TITLE
Fixed timeout of reply messages.

### PR DESCRIPTION
**Pull request by ungureanuvladvictor**
Signed-off-by: Vlad Ungureanu <vvu@vdev.ro>

### CODE REVIEW

**Comment by fnoble** [comment]
cc: @mfine @gsmcmullin

**Comment by gsmcmullin** [comment]
Maybe a comment explaining the dirty dictionary hack?  This is clearly not obvious.

**Comment by mfine** [comment]
Ugh, yeah, that had been fixed in https://github.com/swift-nav/libsbp/pull/183 and https://github.com/swift-nav/libsbp/pull/172 - too many open PRs :( :+1:

**Comment by ungureanuvladvictor** [comment]
Don't you need to set the event ? Didn't see that in the PRs.

**Comment by mfine** [comment]
Sure - I tested it with the timeouts kicking off.

**Pull request merged**
