### PR TITLE
Misc Fixes

### PR DESCRIPTION
**Pull request by fnoble**
- Changes id for `MSG_EPHEMERIS` to `0x46` (#98)
 - Removes annoying timestamps from generated files
 - Fixes `MSG_BOOTLOADER_HANDSHAKE` type spec to fix terminiation issue (#113)
 - Removes the unsupported `bytes` type from the specification

@mookerji @mfine

### CODE REVIEW

**Comment by henryhallam** [comment]
Looks reasonable.

**Comment by fnoble** [comment]
retest this please

**Comment by fnoble** [comment]
retest this please

**Comment by fnoble** [comment]
retest this please

**Comment by fnoble** [comment]
@mookerji : ok it passed this time, must be good to go!

**Pull request merged**
