### PR TITLE
(WIP) Timestamp metadata to ISO 8601

### PR DESCRIPTION
**Pull request by margaret**
for https://github.com/swift-nav/test_team_planning/issues/127
Still need to update the python tests, which are strangely passing despite obviously being wrong 
https://github.com/swift-nav/libsbp/blob/master/python/tests/sbp/client/test_logger.py#L46
/cc @cbeighley @mfine @denniszollo

### CODE REVIEW

**Comment by margaret** [comment]
@JoshuaGross JS tests crashing travis cuz of this http://stackoverflow.com/questions/37677468/error-while-building-r-package-on-travis-ci-tlmgr-update-self-failed

Looks like the fix for that was merged already, though. Any thoughts? :thinking_face:

**Comment by mfine** [comment]
This looks great!

**Comment by margaret** [comment]
Trying the TeX Live installation in a docker container resulted in the same error. I did `tlmgr install --reinstall *` and it said 
```
tlmgr itself needs to be updated.
Please do this via either
 tlmgr update --self
or by getting the latest updater for Unix-ish systems:
 http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh
and/or Windows systems:
 http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.exe
Then continue with other updates as usual.
```
The Unix link redirected to http://ctan.mirrors.hoobly.com/systems/texlive/tlnet/update-tlmgr-latest.sh which seemed to work, except now travis stalls at
```
! LaTeX Error: File `cmbright.sty' not found.

Type X to quit or <RETURN> to proceed,

or enter new name. (Default extension: sty)

Enter file name: 
```
when trying to generate PDF docs :(

**Comment by mfine** [comment]
@margaret let's pull out the latex stuff for now and bring this in and move on!

**Pull request merged**
