### PR TITLE
[ESD-2043] [Review] V4 API

### PR DESCRIPTION
**Pull request by woodfell**
This PR will not be merged. The main PR for the V4 API is #1000. This PR exists in conjunction with #1022 to make reviewing more easy by splitting out related changes and minimising the size of the diff by restricting the new generator.

The goal of this PR is to introduce a new C generator in libsbp which is more portable than the legacy API and free from any compiler extensions. The existing libsbp API (legacy API) has been retained. The new API (V4) exists alongside the legacy API.

This PR is based on #1022 and highlights just the new code which is added to libsbp for the V4 API.

# Design

https://swift-nav.atlassian.net/wiki/spaces/~61688916/pages/1722942301/Design+Doc+-+libsbp

# Implement new generator
https://github.com/swift-nav/libsbp/pull/1023/commits/7a3c52c023912c38ee0df4cb83d5cd585f5f342d

Language bindings in libsbp are generated from a YAML spec by a generator written in python. The challenges which are being addressed by the V4 meant that the legacy C generator was not appropriate, it didn't provide all the required information. 

This commit introduces a new generator for the C headers/source files (c.py) and the test suites (test_c.py). 

In this PR the generator is restricted to generating just a small subset of all SBP messages designed to highlight some corner cases:
- MSG_LOG
- MSG_SV_AZ_EL
- MSG_SETTINGS_READ_BY_INDEX_DONE
- MSG_SETTINGS_READ_BY_INDEX_RESP
- MSG_OBS

and any dependent types

# V4 generated C headers
https://github.com/swift-nav/libsbp/pull/1023/commits/821b3dfe542d74aa0e9eb0ff71ba9c8ee73a5ac6

This commit generates V4 headers from the spec. Due to the artificial restriction in the generator from the previous commit there are a number of empty files created. The files added in this commit demonstrate the structure which are output by the new generator. For a complete set of header files see #1000 

# V4 generated C++ headers
https://github.com/swift-nav/libsbp/pull/1023/commits/5b3d302e4bb69e12f0560ea0a7a7c724f1d9e374

Similar to the previous commit, this generates C++ headers using the V4 generator.

# Hand rolled V4 headers
https://github.com/swift-nav/libsbp/pull/1023/commits/4e614aaaed193f751d9937e241f9ad4afda2eb62

And changes made to the libsbp V4 headers which were done by hand. This includes some restructuring of the legacy API (removing declarations from `sbp.h` which were moved in to other files in #1022`)

# String encoders
https://github.com/swift-nav/libsbp/pull/1023/commits/869d790fafd436e0bf6243524028fd17e61decff

The V4 API adds the ability for libsbp to correctly handle the multiple different string encodings used by SBP on the wire. This commit introduces a series of helper struct and functions which are used internally by libsbp during the encoding/decoding process to handle string. Also includes comprehensive tests

# Generated encode/decode functions
https://github.com/swift-nav/libsbp/pull/1023/commits/f8bca58bed5647f3dca3fb34a3e42ef1d18e6b3d

Generate functions to encode and decode V4 types to/from SBP wire format. As in previous commits this is limited to a small subset of messages. For the complete set see #1022 

# Hand written encode/decode functions
https://github.com/swift-nav/libsbp/pull/1023/commits/7def8f939057d85ef2645554c8ad761afc6b33e3

Functions to encode/decode primitive types to/from wire format. For internal use by libsbp during encode/decode functions.

# Generated test suites
https://github.com/swift-nav/libsbp/pull/1023/commits/969d09d5ddaa31c93a706666d59b1402167a8fc9

Generated from the same test specs as are used to automatically test the legacy API. This uses a new template to use the V4 to send/receive messages and check for validity. Includes code which exercises the string encoders when used in a test spec.

# Hand rolled changes to support V4 API
https://github.com/swift-nav/libsbp/pull/1023/commits/ab55df1e07c6ef0d06a2bfd38213bcaac11a524c

Various other changes written by hand related to implementing the new API. Includes a shuffle in `sbp.c` so that it works properly with both the legacy and V4 API

# Necessary changes to YAML specs
https://github.com/swift-nav/libsbp/pull/1023/commits/16351965117953bc08baf858b9e126b9b67f197d

There are 3 main components in this commit.
1: Update test specs so that the V4 generator can correctly understand new fields
2: Add meta information for string types so the correct string encoder can be selected by the generator
3: Remove the use of a variable length array in an embedded type.

Point 3 is explained in more detail in the design document, one of the SSR embedded types contains a variable length array in an embedded type which makes it impossible to calculate a maximum size for the type (a required part of the new generator). This commit removes the embedded type and moves the fields up to any real messages which make use of that type. This does not change the wire encoding in any way.

### CODE REVIEW

**Comment by silverjam** [comment]
Review progress so far:
- [x] Implement new generator
- [x] V4 generated C headers
- [x] V4 generated C++ headers
- [x] Hand rolled V4 headers
- [ ] String encoders
- [ ] Generated encode/decode functions
- [ ] Hand written encode/decode functions
- [ ] Generated test suites
- [ ] Hand rolled changes to support V4 API
- [ ] Necessary changes to YAML specs

**Comment by silverjam** [comment]
Review progress so far:
- [x] Implement new generator
- [x] V4 generated C headers
- [x] V4 generated C++ headers
- [x] Hand rolled V4 headers
- [x] String encoders
- [x] Generated encode/decode functions
- [x] Hand written encode/decode functions
- [ ] Generated test suites
- [ ] Hand rolled changes to support V4 API
- [ ] Necessary changes to YAML specs

**Comment by silverjam** [comment]
> 
> 
> This is a typo, should have been `greater than` not `less than` - updated to mention validity as well.
> 
> Second point, yes it does serve that purpose. The value passed in to this function from one of the generated wrappers is hardcoded and calculated by the generator. It's specific to each string type field and is the maximum size it can occupy in wire format. in `strnlen` the parameter name is `maxlen` (as least in my version of glibc). Not sure I've got strong feeling about this, can change it to something else if you do

If it's not a pain to change, let's mirror the glibc param name and use `maxlen` too-- I like `limit` personally, but consistency probably has more value for indicating intent here

**Comment by silverjam** [comment]
> 
> 
> Can do that but it will require a bit of reoganisation of the header files. `SBP_MAX_PAYLOAD_LEN` is currently defined in `libsbp/sbp.h`, including that file here would create a circular dependency

Ok, probably not worth the trouble then, or alternately we could define a duplicate constant

**Comment by silverjam** [comment]
Completed my review and this work looks amazing overall, I think we should be ready to merge once we finish the remaining clean-up items and any other issues that shake out from the migration of sbp2nmea to the new API.

A few final housekeeping suggestions:
- I would also recommend running doxygen against the new headers/doc-comments to see how they look, if it turns out that there's a lot of work involved in getting them to render correctly we can defer that to later PR
- We should try compiling something more substantial against the legacy "compat.h", like piksi_firmware_private, or piksi_buildroot/piksi_apps

Re-posting my to-do list in case anyone else wants to use it:
- [x] Implement new generator
- [x] V4 generated C headers
- [x] V4 generated C++ headers
- [x] Hand rolled V4 headers
- [x] String encoders
- [x] Generated encode/decode functions
- [x] Hand written encode/decode functions
- [x] Generated test suites
- [x] Hand rolled changes to support V4 API
- [x] Necessary changes to YAML specs

**Comment by woodfell** [comment]
Thanks @silverjam 

>     * I would also recommend running doxygen against the new headers/doc-comments to see how they look, if it turns out that there's a lot of work involved in getting them to render correctly we can defer that to later PR
I tried running it this morning and to be honest it didn't look great, there were loads of broken links. I'll try to fix it on a new PR


> 
>     * We should try compiling something more substantial against the legacy "compat.h", like piksi_firmware_private, or piksi_buildroot/piksi_apps
Agreed. I'm going to merge #1042 first and then set up portability integration branches in the remaining repos to test everything out

**Comment by woodfell** [comment]
All existing comments have been addressed on https://github.com/swift-nav/libsbp/pull/1042 and merged in to `ESD-2043-portability-project`. Any new comments will be done on a new PR

**Review by GuillaumeDec — APPROVED** [review]
Mostly approving the fact that I've breezed through it and it was very informative to keep us in the loop! Thx Matt! ✅

**Comment by woodfell** [comment]
Any further comments on #1000

**Pull request closed without merging**
